// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "GtkSourceCompletionInfo")]
    pub struct CompletionInfo(Object<ffi::GtkSourceCompletionInfo, ffi::GtkSourceCompletionInfoClass>) @extends gtk::Window, gtk::Bin, gtk::Container, gtk::Widget, @implements gtk::Buildable;

    match fn {
        type_ => || ffi::gtk_source_completion_info_get_type(),
    }
}

impl CompletionInfo {
    pub const NONE: Option<&'static CompletionInfo> = None;

    #[doc(alias = "gtk_source_completion_info_new")]
    pub fn new() -> CompletionInfo {
        assert_initialized_main_thread!();
        unsafe { from_glib_none(ffi::gtk_source_completion_info_new()) }
    }
}

impl Default for CompletionInfo {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for CompletionInfo {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("CompletionInfo")
    }
}
