// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;

glib::wrapper! {
    #[doc(alias = "GtkSourceLanguage")]
    pub struct Language(Object<ffi::GtkSourceLanguage, ffi::GtkSourceLanguageClass>);

    match fn {
        type_ => || ffi::gtk_source_language_get_type(),
    }
}

impl Language {
    pub const NONE: Option<&'static Language> = None;
}

pub trait LanguageExt: 'static {
    #[doc(alias = "gtk_source_language_get_globs")]
    #[doc(alias = "get_globs")]
    fn globs(&self) -> Vec<glib::GString>;

    #[doc(alias = "gtk_source_language_get_hidden")]
    #[doc(alias = "get_hidden")]
    fn is_hidden(&self) -> bool;

    #[doc(alias = "gtk_source_language_get_id")]
    #[doc(alias = "get_id")]
    fn id(&self) -> Option<glib::GString>;

    #[doc(alias = "gtk_source_language_get_metadata")]
    #[doc(alias = "get_metadata")]
    fn metadata(&self, name: &str) -> Option<glib::GString>;

    #[doc(alias = "gtk_source_language_get_mime_types")]
    #[doc(alias = "get_mime_types")]
    fn mime_types(&self) -> Vec<glib::GString>;

    #[doc(alias = "gtk_source_language_get_name")]
    #[doc(alias = "get_name")]
    fn name(&self) -> Option<glib::GString>;

    #[doc(alias = "gtk_source_language_get_section")]
    #[doc(alias = "get_section")]
    fn section(&self) -> Option<glib::GString>;

    #[doc(alias = "gtk_source_language_get_style_fallback")]
    #[doc(alias = "get_style_fallback")]
    fn style_fallback(&self, style_id: &str) -> Option<glib::GString>;

    #[doc(alias = "gtk_source_language_get_style_ids")]
    #[doc(alias = "get_style_ids")]
    fn style_ids(&self) -> Vec<glib::GString>;

    #[doc(alias = "gtk_source_language_get_style_name")]
    #[doc(alias = "get_style_name")]
    fn style_name(&self, style_id: &str) -> Option<glib::GString>;

    #[doc(alias = "hidden")]
    fn connect_hidden_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "id")]
    fn connect_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "name")]
    fn connect_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;

    #[doc(alias = "section")]
    fn connect_section_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<Language>> LanguageExt for O {
    fn globs(&self) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_full(ffi::gtk_source_language_get_globs(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn is_hidden(&self) -> bool {
        unsafe {
            from_glib(ffi::gtk_source_language_get_hidden(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn id(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::gtk_source_language_get_id(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn metadata(&self, name: &str) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::gtk_source_language_get_metadata(
                self.as_ref().to_glib_none().0,
                name.to_glib_none().0,
            ))
        }
    }

    fn mime_types(&self) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_full(ffi::gtk_source_language_get_mime_types(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn name(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::gtk_source_language_get_name(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn section(&self) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::gtk_source_language_get_section(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn style_fallback(&self, style_id: &str) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::gtk_source_language_get_style_fallback(
                self.as_ref().to_glib_none().0,
                style_id.to_glib_none().0,
            ))
        }
    }

    fn style_ids(&self) -> Vec<glib::GString> {
        unsafe {
            FromGlibPtrContainer::from_glib_full(ffi::gtk_source_language_get_style_ids(
                self.as_ref().to_glib_none().0,
            ))
        }
    }

    fn style_name(&self, style_id: &str) -> Option<glib::GString> {
        unsafe {
            from_glib_none(ffi::gtk_source_language_get_style_name(
                self.as_ref().to_glib_none().0,
                style_id.to_glib_none().0,
            ))
        }
    }

    fn connect_hidden_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_hidden_trampoline<P: IsA<Language>, F: Fn(&P) + 'static>(
            this: *mut ffi::GtkSourceLanguage,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Language::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::hidden\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_hidden_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_id_trampoline<P: IsA<Language>, F: Fn(&P) + 'static>(
            this: *mut ffi::GtkSourceLanguage,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Language::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::id\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_id_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_name_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_name_trampoline<P: IsA<Language>, F: Fn(&P) + 'static>(
            this: *mut ffi::GtkSourceLanguage,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Language::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::name\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_name_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    fn connect_section_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_section_trampoline<P: IsA<Language>, F: Fn(&P) + 'static>(
            this: *mut ffi::GtkSourceLanguage,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(Language::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::section\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    notify_section_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for Language {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("Language")
    }
}
